version: "3.9"

services:
  db:
    image: postgres:14
    container_name: mypg
    restart: unless-stopped
    environment:
      POSTGRES_DB: reservation          # BD inicial
      POSTGRES_USER: reservation        # usuario dueño
      POSTGRES_PASSWORD: manager        # contraseña
      TZ: America/Bogota
    ports:
      - "5432:5432"
    volumes:
      # Persistencia de datos
      - dbdata:/var/lib/postgresql/data
      # Scripts de inicialización (solo corren si /var/lib/postgresql/data está vacío)
      - ./db:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    container_name: myapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/reservation
      DB_USER: reservation
      DB_PASS: manager
      TZ: America/Bogota
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
