version: "3.8"

services:
  trainbook:
    build: .
    hostname: trainbookhost
    ports:
      - "8083:8083"
    environment:
      - VERSION=1.0
      - DB_URL=jdbc:postgresql://db:5432/reservation   # ajusta si tu app usa otro nombre
      - DB_USER=reservation
      - DB_PASS=manager
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

  db:
    image: postgres:16
    container_name: postgres-16
    environment:
      - POSTGRES_DB=reservation          # crea la BD
      - POSTGRES_USER=reservation        # crea el usuario
      - POSTGRES_PASSWORD=manager
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d   # aquí pones 01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reservation -d reservation"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks:
      - app_net

# opcional
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@demo.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    networks:
#      - app_net

volumes:
  pg_data:

networks:
  app_net:
